### ISSUE TITLE
field museum occurrence ids are shown, but cannot be linked to field museum specimen page

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/fmnh#1]
hey @magpiedin -

Great to see hundreds of thousands (~115k as of Sept 2021) of field museum biotic associations getting indexed by GloBI.

(via https://www.globalbioticinteractions.org/sources)

![Screenshot from 2021-09-18 15-16-33](https://user-images.githubusercontent.com/1084872/133909921-e085b009-94df-4789-a066-97a72bf46d87.png)

And example search result obtained via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Ffmnh&interactionType=ecologicallyRelatedTo is :

![Screenshot from 2021-09-18 15-19-04](https://user-images.githubusercontent.com/1084872/133909946-5771dfee-5bd7-41ed-b486-7b062b3d889c.png)

or Tubaria romagnesiana adjacent to rotting wood with citation linking to the associated occurrence id -  d1b8ecb4-61df-4882-90a8-e046d4782a7c . 

I found related indexed records at 
https://collections-botany.fieldmuseum.org/catalogue/4338731
![Screenshot from 2021-09-18 15-21-09](https://user-images.githubusercontent.com/1084872/133910075-bc6bcaaa-34bc-4fc1-badd-3e4b1d5cc341.png)

and 
https://www.gbif.org/occurrence/3110151448

How would you like to get the record linked via the GloBI search page? 

Ideally, I'd want to link straight into the Field Museum. 

Please advise.

**Comment by magpiedin** [comment]
Hi Jorrit - Thanks for the heads-up  (Collections folks have been busy :)

To link straight to the FMNH page, if you have the occurrence id, simplest way could be to add this URL-prefix:  

https://db.fieldmuseum.org/

That URL redirects to the collections-zoology/geology/botany/anthropology as appropriate -- e.g.: https://db.fieldmuseum.org/d1b8ecb4-61df-4882-90a8-e046d4782a7c redirects to the collections-botany page you found

If it also helps link to the gbif.org page or pull dwc-data, maybe this?
https://api.gbif.org/v1/occurrence/search?occurrenceId=d1b8ecb4-61df-4882-90a8-e046d4782a7c

All ears if other questions/suggestions

**Comment by rondlg** [comment]
Great news about linking to our pages as Kate sayd (https://db.fieldmuseum.org/d1b8ecb4-61df-4882-90a8-e046d4782a7c). If there is link to the gbif page as well that'd be brilliant.

**Comment by jhpoelen** [comment]
@rondlg @magpiedin thanks for the info. I'll add your prefix to this identifier registry I keep at https://github.com/bio-guoda/preston-identifier-registry . Assuming that the occurrence ids are UUIDs, I imagine such identifier scheme would look like:

```
http[s]{0,1}://db.fieldmuseum.org/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}
```

Let me know if there's another more authoritative, machine-readable list out there.  I'd much like to re-use an existing one out there.

As far as the GBIF occurrence ids - great idea! I was thinking this could be an ad-hoc query when the pages are being loaded for now . A rule could be something like: when you see a Field Museum occurrence id, check whether GBIF has a registration of it, and if it does, render some additional link into the web page.

**Comment by jhpoelen** [comment]
fyi @mielliott

**Comment by magpiedin** [comment]
Just following up here, too -- The FMNH occurrenceId's are currently all UUID4, so that regex should work.  (Very/Long-term, we might end up with a different guid-generator, in case "36-characters" or something more generic helps)

And do you mean a more authoritative/machine-readable list of prefixes?  If so, I don't know of one currently, but might be relevant for [GrSciColl / GrBio](https://www.gbif.org/grscicoll/collection/search) &/or Collection Descriptions -- e.g. [Class:SpecimenIdentifierSystem](https://github.com/tdwg/cd/issues/170)

**Comment by jhpoelen** [comment]
@rondlg @magpiedin Just implemented and deployed a first pass at linking straight into the Field Museum collections . Curious to hear your thoughts. Also, if you are interested in showing that this specimen was indexed by GloBI, you can use something like https://api.globalbioticinteractions.org/exists?accordingTo=https%3A%2F%2Fdb.fieldmuseum.org%2Fb0515046-18af-49a6-9bd9-ad5e23e099e8 . If this returns "OK", then GloBI knows about it, otherwise, it'll return a 404. 

Curious to hear your thoughts!

Example:
1. find indexed field museum interactions via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Ffmnh&interactionType=ecologicallyRelatedTo . see attached image 
![Screenshot from 2021-09-21 23-35-01](https://user-images.githubusercontent.com/1084872/134294420-7fb885f7-5a90-415c-9b49-e427617086ee.png)

2. then, click on document emoji next to occurrence id in "Supported by" (e.g., b0515046-18af-49a6-9bd9-ad5e23e099e8)
3. the url https://db.fieldmuseum.org/b0515046-18af-49a6-9bd9-ad5e23e099e8 redirects to https://collections-botany.fieldmuseum.org/catalogue/4332571 
4. specimen landing page is shown (see attached image) 
![Screenshot from 2021-09-21 23-34-48](https://user-images.githubusercontent.com/1084872/134294365-29a2150a-2fc3-4bb7-a63d-108547f0467e.png)


Also, you can click on the hour-glass to search for that specific specimen within GloBI. This will show you that specimen and all records making similar claims. 

See for example, https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fdb.fieldmuseum.org%2Fb0515046-18af-49a6-9bd9-ad5e23e099e8&interactionType=ecologicallyRelatedTo and attached screenshot. 
![Screenshot from 2021-09-21 23-35-18](https://user-images.githubusercontent.com/1084872/134294339-67664413-8e60-421f-af84-82cf13e931cf.png)

**Comment by rondlg** [comment]
I think it's great - @magpiedin I wonder if there is a way to include a link back to globi from the specimen page in an automated way without having to retrieve links and manually add them to EMu? Similar to the gbif plugin on our emudata page?

**Comment by magpiedin** [comment]
Agreed -- That's really cool to see!

And yup -- or along the [RRC cross-ref's to IPNI/etc](https://plantidtools.fieldmuseum.org/en/rrc/catalogue/203677), could see if Pete could give Jorrit's example a try for specimen-pages:

if [https://api.globalbioticinteractions.org/exists?accordingTo=https://db.fieldmuseum.org/ + `occurrenceId` ](https://api.globalbioticinteractions.org/exists?accordingTo=https%3A%2F%2Fdb.fieldmuseum.org%2Fb0515046-18af-49a6-9bd9-ad5e23e099e8)
= "OK"

then display link to:
[https://www.globalbioticinteractions.org/?accordingTo=https://db.fieldmuseum.org/ + `occurrenceId` + &interactionType=ecologicallyRelatedTo](https://www.globalbioticinteractions.org/?accordingTo=https://db.fieldmuseum.org/b0515046-18af-49a6-9bd9-ad5e23e099e8&interactionType=ecologicallyRelatedTo)

**Comment by jhpoelen** [comment]
@rondlg @magpiedin bi-directional links sound like fun! Happy to make changes when needed.

Note that for  [https://api.globalbioticinteractions.org/exists?accordingTo=https://db.fieldmuseum.org/ + `occurrenceId` ](https://api.globalbioticinteractions.org/exists?accordingTo=https%3A%2F%2Fdb.fieldmuseum.org%2Fb0515046-18af-49a6-9bd9-ad5e23e099e8) you can get away with just checking the http status code == 200 , no need to parse the content "OK". That "OK" is just there for instant gratification for us humans. 

Oh, and @magpiedin thanks for sharing the links to the collection registry . . . wouldn't it be neat if we can come up with some extended/ complimentary registry that translates occurrence ids / institution code / collection code / into a list of location where you can find stuff about them? 

It'd be neat to repeat this example across all specimen GloBI indexes . . . across institutions and collections.

**Comment by jhpoelen** [comment]
for recent example of neat linked Field Museum record see - 
https://github.com/globalbioticinteractions/globalbioticinteractions/issues/616#issuecomment-1636571657

any update on the link back from EMu to GloBI?

**Comment by jhpoelen** [comment]
Closing this issue. Linkback from EMu to GloBI is a separate topic.
