### ISSUE TITLE
institution id [FMNH] and [F] are used 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/fmnh#2]
As I was poking around indexed records for flying squirrel (_Glaoucomys oregonensis_) inspired by #SquirrelAwarenessMonth tweets by https://twitter.com/KayceCBell (e.g., https://twitter.com/KayceCBell/status/1444681411487670284 ), I stumbled across a Glaoucomys sp. ectoparasite _Orchopeas  fulleri_ specimen https://collections-zoology.fieldmuseum.org/catalogue/4355428 with occurrence id 8278596f-4d3f-4f82-8cd1-b5070fe1bc7c . 

I was a bit bummed to find out that the record was not linked directly to a Field Museum specimen page via GloBI (see attached screenshot), despite the field museum redirect from https://db.fieldmuseum.org/8278596f-4d3f-4f82-8cd1-b5070fe1bc7c to https://collections-zoology.fieldmuseum.org/catalogue/4355428 just fine (see attached).

After some digging, I found that the listed institution code is "FMNM" instead of the expected "F". 

@magpiedin curious to hear why you are using both "F" and "FMNM" as institutionCode for the field museum.

![Screenshot from 2021-10-04 10-19-37](https://user-images.githubusercontent.com/1084872/135895931-1bad1702-364d-4470-8484-6cdb37e01464.png)

![Screenshot from 2021-10-04 10-20-00](https://user-images.githubusercontent.com/1084872/135895948-2278d5ce-aa58-4b96-bb76-4bc15484d50f.png)

The corresponding indexed GBIF record appears to be:

https://www.gbif.org/occurrence/3302590331 (see attached screenshot)

![Screenshot from 2021-10-04 10-25-37](https://user-images.githubusercontent.com/1084872/135896498-89a66117-8426-4aeb-a66f-0970cabbfd36.png)

**Comment by jhpoelen** [comment]
I've added ```FMNH``` in addition to ```F``` as an institutionCode alias for the Field Museum .

**Comment by fmjjones** [comment]
F is used mainly by Botany as it is the "official" Botany acronym (listed in Index Herbariorum) and FMNH is used by all other disciplines as the official acronym.

**Comment by jhpoelen** [comment]
@fmjjones thanks for clarifying Janeen . I keep looking for some registry that links the institution codes, and specimen landing page URL patterns. Please let me know if there is something like that . . . otherwise, we might have to build one. ; )
